export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const CHECK_AUTH_STATUS = 'CHECK_AUTH_STATUS'
export const CREATE_USER = 'CREATE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'

export const CREATE_GAME = 'CREATE_GAME'
export const UPDATE_GAME = 'UPDATE_GAME'
export const DELETE_GAME = 'DELETE_GAME'

export const CREATE_NEW_QUESTION = 'CREATE_NEW_QUESTION'
export const UPDATE_QUESTION = 'UPDATE_QUESTION'
export const SAVE_PENDING_QUESTION = 'SAVE_PENDING_QUESTION'
export const DELETE_QUESTION = 'DELETE_QUESTION'

export const UPDATE_PENDING_QUESTION = 'UPDATE_PENDING_QUESTION'

export const CREATE_ENTRY = 'CREATE_ENTRY'
export const UPDATE_ENTRY = 'UPDATE_ENTRY'
export const DELETE_ENTRY = 'DELETE_ENTRY'
export const FETCH_ENTRY = 'FETCH_ENTRY'
export const SET_ENTRY = 'SET_ENTRY'

export const CREATE_POSSIBLE_ANSWER = 'CREATE_POSSIBLE_ANSWER'
export const UPDATE_POSSIBLE_ANSWER = 'UPDATE_POSSIBLE_ANSWER'
export const DELETE_POSSIBLE_ANSWER = 'DELETE_POSSIBLE_ANSWER'

export const UPDATE_PENDING_POSSIBLE_ANSWER = 'UPDATE_PENDING_POSSIBLE_ANSWER'
export const SAVE_PENDING_POSSIBLE_ANSWER = 'SAVE_PENDING_POSSIBLE_ANSWER'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD'
export const UPDATE_NEW_GROUP_NAME = 'UPDATE_NEW_GROUP_NAME'
export const UPDATE_NEW_ENTRY_NAME = 'UPDATE_NEW_ENTRY_NAME'

export const SUBMIT_SEARCH = 'SUBMIT_SEARCH'
export const SUBMIT_SEARCH_SUCCESS = 'SUBMIT_SEARCH_SUCCESS'
export const SUBMIT_SEARCH_FAILURE = 'SUBMIT_SEARCH_FAILURE'
export const SAVE_TITLE = 'SAVE_TITLE'
export const SAVE_PERSON = 'SAVE_PERSON'

export const CREATE_NEW_GAME = 'CREATE_NEW_GAME'
export const UPDATE_PENDING_GAME = 'UPDATE_PENDING_GAME'
export const SAVE_PENDING_GAME = 'SAVE_PENDING_GAME'

export const CREATE_GROUP = 'CREATE_GROUP'
export const SET_GROUP = 'SET_GROUP'
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS'
export const FETCH_GROUP = 'FETCH_GROUP'
